travis:
  secure:
    BINSTAR_TOKEN: gWRYM5JWT+FRfEeb1/jFyybCDxSNjfIdDeRk7O0T5AJHaB/glnWRiOO2XUzPdxCTbNUDO+VIZh+SLCBYlY3cGZ6Fc68+GRdEpK8x6nno1JeEe+28VVOpiplPgBBwpvnV7lOzdRF08AO2t/dEaymscfwaCVLYONhQ4R514TuS1arggYwZEC/vwots4/3O4mvR50JmNHq3Xw4rG5l0tDex873yxgw+xxQm7+U2blQOV3YnpP5+xWtAuWUPAlpppihvoIwYMOLN/TJ4tgXQTt6opygAExQiKp6zbfMOz6AmWrlkmi6AcV1DYAByNk14a5xdxbLS7DiIsaNQSUHzGWqHZN1Srwn6G25XzjY1U3WmzSuimAzvAyMlPi9srCjIyp2bfBc1byrm1jmxID2poftCZBFNaqDPEccm3DN1hyjCiLKs/LqclCnrMd7+/H+P6tp6+t3uTIMTSTr0xiPs4g1eDAEC4Mms4m7fiKBFTeBDgRcfPsBa4wAorPqJmXWzFBTEEEDuNlT8yo0WLSc86n1bmW9wEwdvUt+Zu7FroqwbHCPn/cqJoOorV9vPvoBCiCq8sPHbe0sVO7/sEUQqSwJmGemNy6JfzxWTq4eDLZ6M7BeNeWXxYbXvP7meGjWdHmUEVk3tZcGIDDj6PVZDXf3UR1W2Iqi8L1H4xo6Qxm51rt8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
